# Generated by Django 4.1.1 on 2022-09-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('idkaryawan', models.AutoField(primary_key=True, serialize=False)),
                ('namakaryawan', models.CharField(max_length=50)),
                ('kontakkaryawan', models.IntegerField()),
                ('jobdesk', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('idproduk', models.AutoField(primary_key=True, serialize=False)),
                ('namaproduk', models.CharField(max_length=50)),
                ('satuanproduk', models.CharField(max_length=10)),
                ('hargaproduk', models.IntegerField()),
                ('kategoriproduk', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('idpenjualan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalpenjualan', models.DateField()),
                ('namapelanggan', models.CharField(max_length=50)),
                ('idkaryawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='pembelian',
            fields=[
                ('idpembelian', models.AutoField(primary_key=True, serialize=False)),
                ('tanggaltransaksi', models.DateField()),
                ('namasupplier', models.CharField(max_length=50)),
                ('idkaryawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='detailpenjualan',
            fields=[
                ('iddetailpenjualan', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitasproduk', models.IntegerField()),
                ('idpenjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjualan')),
                ('idproduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produk')),
            ],
        ),
        migrations.CreateModel(
            name='detailpembelian',
            fields=[
                ('iddetailpembelian', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitasproduk', models.IntegerField()),
                ('idpembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembelian')),
                ('idproduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produk')),
            ],
        ),
    ]
